def configuredRepoUrl = System.getenv('MAVEN_REPOSITORY_URL') ?: findProperty('mavenRepositoryUrl')

buildscript {
    repositories {
        def pluginRepoUrl = System.getenv('MAVEN_REPOSITORY_URL')
        if (pluginRepoUrl) {
            maven { url pluginRepoUrl }
        }
        mavenCentral()
    }
    dependencies {
        classpath 'org.springframework.boot:spring-boot-gradle-plugin:3.3.5'
    }
}

apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: 'org.springframework.boot'
apply plugin: 'io.spring.dependency-management'
apply plugin: 'jacoco'

group = 'org.recap'
version = '0.0.1-SNAPSHOT'
description = 'scsb-etl'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    if (configuredRepoUrl) {
        maven { url configuredRepoUrl }
    }
    mavenCentral()
}

ext {
    camelVersion = '4.8.1'
}

dependencies {
    implementation "org.apache.camel.springboot:camel-spring-boot-starter:${camelVersion}"
    implementation "org.apache.camel.springboot:camel-metrics-starter:${camelVersion}"
    implementation "org.apache.camel.springboot:camel-ftp-starter:${camelVersion}"
    implementation "org.apache.camel.springboot:camel-csv-starter:${camelVersion}"
    implementation "org.apache.camel.springboot:camel-bindy-starter:${camelVersion}"
    implementation "org.apache.camel.springboot:camel-mail-starter:${camelVersion}"
    implementation "org.apache.camel.springboot:camel-stream-starter:${camelVersion}"
    implementation "org.apache.camel.springboot:camel-jaxb-starter:${camelVersion}"
    implementation "org.apache.camel.springboot:camel-zipfile-starter:${camelVersion}"
    implementation "org.apache.camel.springboot:camel-activemq-starter:${camelVersion}"

    implementation 'org.apache.commons:commons-csv:1.11.0'
    implementation 'org.apache.commons:commons-lang3:3.16.0'
    implementation 'commons-io:commons-io:2.17.0'
    implementation 'commons-beanutils:commons-beanutils:1.9.4'
    implementation 'com.google.guava:guava:33.3.1-jre'

    implementation 'org.apache.activemq:activemq-broker:6.1.3'
    implementation 'org.apache.activemq:activemq-pool:6.1.3'

    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-validation'

    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.6.0'

    implementation 'info.freelibrary:freelib-marc4j:2.6.12'
    runtimeOnly 'com.mysql:mysql-connector-j'

    implementation 'jakarta.xml.bind:jakarta.xml.bind-api:4.0.2'
    implementation 'org.glassfish.jaxb:jaxb-runtime:4.0.5'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.restdocs:spring-restdocs-mockmvc'
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()
    systemProperties = System.properties
}

jacocoTestReport {
    reports {
        xml.required = true
        csv.required = false
        html.required = true
        html.outputLocation = layout.buildDirectory.dir('jacocoHtml')
    }
}

tasks.register('scsbEtlJavadocs', Javadoc) {
    source = sourceSets.main.allJava
    classpath = configurations.compileClasspath
    options.addStringOption('Xdoclint:none', '-quiet')
    def home = System.getProperty('user.home')
    destinationDir = file("${home}/scsb-javadocs/scsb-etl")
}
